### PR TITLE
Further 0.8 fixes

### PR DESCRIPTION
**Pull request by cs96and**
Get initial lighting information from token.data, rather than token.lighting.

Data in token.lighting may not be complete if the token has never had lighting enabled on it.  Also, the data is restored to token.data (via token.document), so it makes sense that that is the location it is initially saved from.

### CODE REVIEW

**Comment by mr-barakas** [comment]
The new code is working for me.  Very nice work!

**Comment by Haladesta** [comment]
It seems to work for me now as well mostly.
The only thing is that when it reads the light color in the token to store it when enabling the light, it throws an exception whenever the field for light color is empty.

> torchlight.js:431 Initialisation
> torchlight.js:96 Clicked on the light button when the light is off.
>
> torchlight.js:375 Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
>     at storeTokenLighting (torchlight.js:375)
>     at onButtonClick (torchlight.js:104)
>
> storeTokenLighting @ torchlight.js:375
> onButtonClick @ torchlight.js:104

**Comment by cs96and** [comment]
@Haladesta, I'm not sure you are using the latest version, as the line numbers mentioned in the console messages are off.  E.g. `toString()` is called on line 377, not 375, and is guarded with an `undefined` variable check.

**Comment by Haladesta** [comment]
Ahh, ok I found it. I didn't know I had to look at your repo instead of this one. Works now 👍

**Comment by PhilippeKr** [comment]
Many thanks, it seems to be working for me as well, let me prepare the packaging, I'll try to upload is shortly.

**Comment by PhilippeKr** [comment]
OK, I have created version 0.10.0, and uploaded it to Foundry, it seems available and working well. Thanks for all the help !

**Comment by cs96and** [comment]
@PhilippeKr, thanks for doing the release.  I notice on the foundry page you have marked v0.10.0 as compatible with foundry version 0.7.5 to 0.8.6...
https://foundryvtt.com/packages/torchlight/

However I don't think the latest changes are compatible with 0.7.x.  You will need to continue using v0.9.0 for 0.7.x.

I changed the module.json manifest to only be compatible with 0.8.6 - 0.8.7

**Comment by cs96and** [comment]
Also, I noticed that the .zip file contains an .archive folder and two temporary files (ziCHO0u1 and ziDOEkw1) which appear to be zip files themselves.

Not a major issue, but just bloats out the module.

**Comment by PhilippeKr** [comment]
You're right, it was a field that is too much on the right on the Foundry form, which made me miss it, it is hopefully corrected. And I've modified the .zip as well, although the bloating really comes from the images in the doc folder, I have uploaded a new version, let me know if it's OK.

**Pull request merged**
